trigger:
  branches:
    include:
      - main
  paths:
    include:
      - jobs
      - stages
      - steps
      - variables

pr:
  branches:
    include:
      - main
  paths:
    include:
      - jobs
      - stages
      - steps
      - variables

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Validate
    displayName: Validate
    jobs:
      - job: Validate
        displayName: Validate commits
        steps:
          - script: |
              npm install
              npm run commitlint:ci
            displayName: Run commitlint
        workspace:
          clean: all
  - stage: Release
    condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/main'))
    displayName: Release
    dependsOn: Validate
    jobs:
      - job: Release
        displayName: Create release version
        steps:
          - checkout: self
            clean: true
            persistCredentials: true
          - script: |
              npm install
              npm run release
            displayName: Run release
