# A pipeline template for running checks against a Terraform project
# Checks formatting, linting, checkov, and validates
# assumes a single terraform directory

parameters:
  - name: pool
    type: object
    default:
      name: pins-odt-agent-pool
  - name: workingDirectory
    type: string
    default: $(System.DefaultWorkingDirectory)
  - name: tflintConfigPath
    type: string
  - name: gitFetchDepth # see https://learn.microsoft.com/en-us/azure/devops/pipelines/repos/azure-repos-git?view=azure-devops&tabs=yaml#shallow-fetch
    type: number
    default: 1
  - name: terraformVersion
    type: string
    default: 'latest' # defaults to whichever is latest on the agent

stages:
  - template: ../stages/wrapper_stage.yml
    parameters:
      name: Run Checks
      pool: ${{ parameters.pool }}
      jobs:
        - template: ../jobs/wrapper_job.yml
          parameters:
            name: Validate Terraform
            steps:
              - checkout: self
                clean: true
                persistCredentials: true
                fetchDepth: ${{ parameters.gitFetchDepth }}
              - template: ../steps/check_branch_name.yml
              - template: ../steps/git_tagging.yml
              - script: |
                  echo "Using terraform version ${{ parameters.terraformVersion }}"
                  tfenv use ${{ parameters.terraformVersion }}
                displayName: Set Terraform Version
              - template: ../steps/terraform_format.yml@templates
              - template: ../steps/terraform_validate.yml@templates
                parameters:
                  workingDirectory: ${{ parameters.workingDirectory }}
              - template: ../steps/terraform_tflint.yml@templates
                parameters:
                  tflintConfigPath: ${{ parameters.tflintConfigPath }}
                  moduleDirectories:
                    - ${{ parameters.workingDirectory }}
              - template: ../steps/run_checkov.yml@templates
