parameters:
  - name: cypressGroupName
    type: string
  - name: cypressJsonPath
    type: string
    default: cypress/cucumber-json
  - name: cypressRecordKey
    type: string
  - name: cypressReportPath
    type: string
    default: cypress/cucumber-report
  - name: cypressScreenshotsPath
    type: string
    default: cypress/screenshots
  - name: nodeVersion
    type: string
    default: 16
  - name: pool
    type: object
    default:
      name: pins-odt-agent-pool-tests
  - name: postTestRunSteps
    type: stepList
    default: []
  - name: preTestRunSteps
    type: stepList
    default: []
  - name: strategy
    type: object
    default:
      parallel: 10
  - name: workingDirectory
    type: string
    default: $(Build.Repository.LocalPath)

jobs:
  - job: Cypress_e2e_tests
    displayName: Run Cypress E2E Tests
    pool: ${{ parameters.pool }}
    strategy: ${{ parameters.strategy }}
    steps:
      - task: Cache@2
        inputs:
          key: npm | $(Agent.OS) | package-lock.json
          path: /home/AzDevOps/.npm
          restoreKeys: npm | $(Agent.OS) | package-lock.json
        displayName: Cache NPM packages
      - task: Cache@2
        inputs:
          cacheHitVar: CYPRESS_CACHE_RESTORED
          key: cypress | $(Agent.OS) | package-lock.json
          path: /home/AzDevOps/.cache/Cypress
          restoreKeys: cypress | $(Agent.OS) | package-lock.json
        displayName: Cache Cypress binary
      - ${{ each step in parameters.preTestRunSteps }}:
        - ${{ step }}
      - template: ../steps/cypress_run_e2e_tests.yml
        parameters:
          cypressGroupName: ${{ parameters.cypressGroupName }}
          cypressJsonPath: ${{ parameters.cypressJsonPath }}
          cypressRecordKey: ${{ parameters.cypressRecordKey }}
          cypressReportPath: ${{ parameters.cypressReportPath }}
          cypressScreenshotsPath: ${{ parameters.cypressScreenshotsPath }}
          nodeVersion: ${{ parameters.nodeVersion }}
          workingDirectory: ${{ parameters.workingDirectory }}
      - ${{ each step in parameters.postTestRunSteps }}:
        - ${{ step }}
  - job: Publish_artifacts
    condition: always()
    dependsOn: Cypress_e2e_tests
    displayName: Publish test artifacts
    pool: ${{ parameters.pool }}
    steps:
      - checkout: none
      - script: |
          if [[ -d "screenshots" ]]; then
            echo "Screenshots exist"
            echo "##vso[task.setvariable variable=publishScreenshots]true"
          fi

          if [[ -d "screenshots" ]]; then
            echo "JSON files exist"
            echo "##vso[task.setvariable variable=publishJson]true"
          fi

          if [[ -d "screenshots" ]]; then
            echo "Reports exist"
            echo "##vso[task.setvariable variable=publishReports]true"
          fi
        displayName: Check artifacts exist
        workingDirectory: $(Build.ArtifactStagingDirectory)
      - publish: $(Build.ArtifactStagingDirectory)/screenshots
        artifact: screenshots
        condition: eq(variables['publishScreenshots'], 'true')
        displayName: Publish screenshots
      - publish: $(Build.ArtifactStagingDirectory)/cucumber-json
        artifact: cucumber-json
        condition: eq(variables['publishJson'], 'true')
        displayName: Publish cucumber json files
      - publish: $(Build.ArtifactStagingDirectory)/cucumber-report
        artifact: cucumber-report
        condition: eq(variables['publishReports'], 'true')
        displayName: Publish reports
