parameters:
  - name: condition
    type: string
    default: succeeded()
  - name: container
    type: string
    default: ''
  - name: dependsOn
    type: object
    default: []
  - name: name
    type: object
  - name: steps
    type: stepList
  - name: variables
    type: object
    default: []

jobs:
  - job: ${{ replace(replace(parameters.name, '-', '_'), ' ', '_') }}
    condition: ${{ parameters.condition }}
    ${{ if parameters.container }}:
      container: ${{ parameters.container }}
    dependsOn:
      - ${{ each dependsOn in parameters.dependsOn }}:
        - ${{ dependsOn }}
    displayName: ${{ parameters.name }}
    steps:
      - ${{ each step in parameters.steps }}:
        - ${{ step }}
    variables:
      - ${{ each variable in parameters.variables }}:
        - ${{ variable }}
    workspace:
      clean: all
