parameters:
  - name: azureLogin
    type: boolean
    default: false
  - name: condition
    type: string
    default: succeeded()
  - name: dependsOn
    type: object
    default: []
  - name: environment
    type: string
    default: Dev
  - name: name
    type: object
  - name: project
    type: string
    default: ''
  - name: steps
    type: stepList
  - name: variables
    type: object
    default: []

jobs:
  - job: ${{ replace(replace(parameters.name, '-', '_'), ' ', '_') }}
    condition: ${{ parameters.condition }}
    dependsOn:
      - ${{ each dependsOn in parameters.dependsOn }}:
        - ${{ dependsOn }}
    displayName: ${{ parameters.name }}
    steps:
      - ${{ if eq(parameters.azureLogin, 'true') }}:
        - template: ../steps/azure_cli_login.yml
          parameters:
            azureServiceConnection: ${{ parameters.project }}-${{ parameters.environment }}
      - ${{ each step in parameters.steps }}:
        - ${{ step }}
    variables:
      - ${{ each variable in parameters.variables }}:
        - ${{ variable }}
    workspace:
      clean: all
