variables:
  - name: CONTAINER_REGISTRY_SUBSCRIPTION_ID
    value: edb1ff78-90da-4901-a497-7e79f966f8e2
  - name: ENVIRONMENT
    value: dev
  - name: KEY_VAULT_NAME
    value: pinskvcommondevukw001
  - name: SUBSCRIPTION_ID
    value: 962e477c-0f3b-4372-97fc-a198a58e259e
