variables:
  - name: CONTAINER_REGISTRY_SUBSCRIPTION_ID
    value: edb1ff78-90da-4901-a497-7e79f966f8e2
  - name: ENVIRONMENT
    value: prod
  - name: KEY_VAULT_NAME
    value: pinskvcommonprodukw001
  - name: SUBSCRIPTION_ID
    value: d1d6c393-2fe3-40af-ac27-f5b6bad36735
