variables:
  - name: CONTAINER_REGISTRY_SUBSCRIPTION_ID
    value: edb1ff78-90da-4901-a497-7e79f966f8e2
  - name: ENVIRONMENT
    value: staging
  - name: SUBSCRIPTION_ID
    value: 76cf28c6-6fda-42f1-bcd9-6d7dbed704ef
