variables:
  - name: CONTAINER_REGISTRY_SUBSCRIPTION_ID
    value: edb1ff78-90da-4901-a497-7e79f966f8e2
  - name: ENVIRONMENT
    value: training
  - name: KEY_VAULT_NAME
    value: pinskvcommontrainingukw
  - name: SUBSCRIPTION_ID
    value: dbfbfbbf-eb6f-457b-9c0c-fe3a071975bc
