parameters:
  - name: appName
    type: string
  - name: artifactSourcePipeline
    type: string
  - name: azurecrName
    type: string
  - name: azurecrServiceConnection
    type: string
  - name: container
    type: string
    default: ''
  - name: deploymentTag
    type: string
  - name: environments
    type: object
    default:
      - name: Dev
      - name: Test
        dependsOn:
          - Dev
      - name: Prod
        dependsOn:
          - Test
  - name: globalVariables
    type: object
    default: []
  - name: projectName
    type: string
  - name: region
    type: string
    default: UK West
    values:
      - UK West
      - UK South
  - name: releaseVersion
    type: string
  - name: repository
    type: string
  - name: variables
    type: object
    default: []
  - name: workingDirectory
    type: string
    default: $(System.DefaultWorkingDirectory)

variables:
  - ${{ each var in parameters.globalVariables }}:
    - ${{ var }}
  - ${{ if eq(parameters.deploymentTag, 'none') }}:
    - name: deploymentTag
      value: $[replace(replace(variables['Build.SourceBranch'], 'refs/heads/', ''), '/', '.')]
  - ${{ else }}:
    - name: deploymentTag
      value: ${{ parameters.deploymentTag }}
  - ${{ if eq(parameters.region, 'UK West') }}:
    - name: REGION_SHORT
      value: ukw
    - name: REGION_SLUG
      value: uk-west
  - ${{ if eq(parameters.region, 'UK South') }}:
    - name: REGION_SHORT
      value: uks
    - name: REGION_SLUG
      value: uk-south

stages:
  - ${{ each environment in parameters.environments }}:
    - template: ./wrapper_stage.yml
      parameters:
        dependsOn:
          - ${{ each dependsOn in environment.dependsOn }}:
            - Deploy_${{ dependsOn }}
        jobs:
          - template: ../jobs/wrapper_deployment.yml
            parameters:
              container: ${{ parameters.container }}
              environment: ${{ environment.name }}
              name: Deploy ${{ environment.name }}
              steps:
                - task: DownloadPipelineArtifact@2
                  displayName: Download Docker Image
                  inputs:
                    allowPartiallySucceededBuilds: true
                    pipeline: ${{ parameters.artifactSourcePipeline }}
                    project: $(System.TeamProject)
                    source: specific
                    tags: $(deploymentTag)
                - template: ../steps/acr_auth.yml
                  parameters:
                    azurecrName: ${{ parameters.azurecrName }}
                    azurecrServiceConnection: ${{ parameters.azurecrServiceConnection }}
                - template: ${{variables['Build.SourcesDirectory']}}/steps/azure_web_app_deploy.yml@templates
                  parameters:
                    appName: ${{ parameters.appName }}
                    artifactSourcePipeline: ${{ parameters.artifactSourcePipeline }}
                    azurecrName: ${{ parameters.azurecrName }}
                    azureEnvironmentServiceConnection: ${{ parameters.projectName }}-${{ lower(environment.name) }}
                    deploymentTag: $(deploymentTag)
                    releaseVersion: ${{ parameters.releaseVersion }}
                    repository: ${{ parameters.repository }}
        name: Deploy ${{ environment.name }}
        variables:
          - template: ../variables/environments/${{ lower(environment.name) }}.yml
          - ${{ each var in parameters.variables }}:
            - ${{ var }}
        workingDirectory: ${{ parameters.workingDirectory }}
