parameters:
  - name: deploymentStages
    type: object
#   example:
#     - name: Plan
#       authType: terraform 
#       container: terraform-tooling
#       deploymentSteps:
#         - template: $(WORKING_DIRECTORY)/steps/terragrunt_plan_all.yml
#       isDeployment: false
#     - name: Deploy Container
#       authType: acr 
#       azurecrName: pinscontainerregistry
#       dependsOnDeploymentStages:
#         - Plan
#       deploymentSteps:
#         - template: $(WORKING_DIRECTORY)/steps/azure_web_app_deploy.yml
  - name: environments
    type: object
#   example:
#     - name: Dev
#       variables: 
#         - template: variables/dev.yml
#     - name: Test
#       dependsOn:
#         - Dev
#       variables:
#         - template: variables/test.yml
  - name: globalVariables
    type: object
    default: []
  - name: pool
    type: object
    default:
      name: pins-odt-agent-pool
    type: string
    default: pins-odt-agent-pool
  - name: project
    type: string
  - name: variables
    type: object
    default: []
  - name: workingDirectory
    type: string
    default: $(System.DefaultWorkingDirectory)
  
variables:
  - ${{ each var in parameters.globalVariables }}:
    - ${{ var }}

stages:
  - ${{ each environment in parameters.environments }}:
    - ${{ each stage in parameters.deploymentStages }}:
      - template: ./wrapper_stage.yml
        parameters:
          condition: ${{ stage.condition }}
          dependsOn:
            - ${{ each dependsOn in environment.dependsOn }}:
              - ${{ replace(replace(stage.name, '-', '_'), ' ', '_') }}_${{ dependsOn }}
            - ${{ if stage.dependsOn }}:
              - ${{ each dependsOnStage in stage.dependsOn }}:
                - ${{ replace(replace(dependsOnStage, '-', '_'), ' ', '_') }}_${{ environment.name }}
          jobs:
            - ${{ if eq(stage.isDeployment, 'false') }}:
              - template: ../jobs/wrapper_job.yml
                parameters:
                  container: ${{ stage.container }}
                  name: ${{ stage.name }} ${{ environment.name }}
                  steps:
                    - ${{ if eq(stage.authType, 'terraform') }}:
                      - template: ../steps/terraform_azure_cli_auth.yml
                        parameters:
                          azureServiceConnection: ${{ parameters.project }}-${{ environment.name }}
                    - ${{ if eq(stage.authType, 'acr') }}:
                      - template: ../steps/acr_auth.yml
                        parameters:
                          azurecrName: ${{ stage.azurecrName }}
                          azurecrServiceConnection: ${{ parameters.project }}-tooling
                    - ${{ if stage.deploymentSteps }}:
                      - ${{ each deploymentStep in stage.deploymentSteps }}:
                        - ${{ deploymentStep }}
                    - ${{ if eq(coalesce(stage.deploymentSteps, false), false) }}:
                      - ${{ each deploymentStep in parameters.deploymentSteps }}:
                        - ${{ deploymentStep }}
                  variables:
                    - ${{ if stage.variables }}:
                      - ${{ each var in stage.variables }}:
                        - ${{ var }}
            - ${{ else }}:
              - template: ../jobs/wrapper_deployment.yml
                parameters:
                  artifact: ${{ stage.artifact }}
                  container: ${{ stage.container }}
                  environment: ${{ environment.name }}
                  name: ${{ stage.name }} ${{ environment.name }}
                  steps:
                    - ${{ if eq(stage.authType, 'terraform') }}:
                      - template: ../steps/terraform_azure_cli_auth.yml
                        parameters:
                          azureServiceConnection: ${{ parameters.project }}-${{ environment.name }}
                    - ${{ if eq(stage.authType, 'acr') }}:
                      - template: ../steps/acr_auth.yml
                        parameters:
                          azurecrName: ${{ stage.azurecrName }}
                          azurecrServiceConnection: ${{ parameters.project }}-${{ environment.name }}
                    - ${{ if stage.deploymentSteps }}:
                      - ${{ each deploymentStep in stage.deploymentSteps }}:
                        - ${{ deploymentStep }}
                  variables:
                    - ${{ if stage.variables }}:
                      - ${{ each var in stage.variables }}:
                        - ${{ var }}
          pool: ${{ parameters.pool }}
          name: ${{ stage.name }} ${{ environment.name }}
          variables:
            - template: ../variables/environments/${{ lower(environment.name) }}.yml
            - ${{ each var in parameters.variables }}:
              - ${{ var }}
            - ${{ each var in environment.variables }}:
              - ${{ var }}
          workingDirectory: ${{ parameters.workingDirectory }}
