parameters:
  - name: artifact
    type: string
    default: ''
  - name: automaticDeployments
    type: object
    default:
      environments:
        - name: Dev
  - name: azureAuth
    type: boolean
    default: true
  - name: deploymentStages
    type: object
#   example:
#     - name: Plan
#       container: terraform-tooling
#       deploymentSteps:
#         - template: $(WORKING_DIRECTORY)/steps/terragrunt_plan_all.yml
#       isDeployment: false
#       variables:
#         - name: myVar
#           value: myString
#     - name: Apply
#       artifact: terraform-plan
#       condition: succeeded()
#       dependsOn:
#         - Plan
#       deploymentSteps:
#         - template: $(WORKING_DIRECTORY)/steps/terragrunt_apply_all.yml
  - name: downloadArtifact 
    type: boolean
    default: false
  - name: environments
    type: object
    default:
      - name: Dev
      - name: Test
        dependsOn:
          - Dev
      - name: Prod
        dependsOn:
          - Test
  - name: globalVariables
    type: object
    default: []
  - name: pool
    type: object
    default:
      name: pins-odt-agent-pool
  - name: region
    type: string
    default: UK West
    values:
      - UK West
      - UK South
  - name: sourcePipeline
    type: string
    default: ''
  - name: workingDirectory
    type: string
    default: $(System.DefaultWorkingDirectory)
  
variables:
  - ${{ each var in parameters.globalVariables }}:
    - ${{ var }}
  - group: pipeline_secrets

stages:
  - ${{ if in(variables['Build.Reason'], 'IndividualCI', 'BatchedCI', 'ResourceTrigger') }}:
    - ${{ if ne(parameters.automaticDeployments, '') }}:
      - ${{ each environment in parameters.automaticDeployments.environments }}:
        - ${{ each stage in parameters.deploymentStages }}:
          - template: ./wrapper_stage.yml
            parameters:
              condition: ${{ stage.condition }}
              dependsOn:
                - ${{ each dependsOn in environment.dependsOn }}:
                  - ${{ replace(replace(stage.name, '-', '_'), ' ', '_') }}_${{ dependsOn }}
                - ${{ if stage.dependsOn }}:
                  - ${{ each dependsOnStage in stage.dependsOn }}:
                    - ${{ replace(replace(dependsOnStage, '-', '_'), ' ', '_') }}_${{ environment.name }}
              jobs:
                - ${{ if eq(stage.isDeployment, 'false') }}:
                  - template: ../jobs/wrapper_job.yml
                    parameters:
                      container: ${{ stage.container }}
                      name: ${{ stage.name }} ${{ environment.name }}
                      steps:
                        - ${{ if parameters.azureAuth }}:
                          - template: ../steps/azure_auth.yml
                            parameters:
                              subscriptionId: $(SUBSCRIPTION_ID)
                        - ${{ if stage.deploymentSteps }}:
                          - ${{ each deploymentStep in stage.deploymentSteps }}:
                            - ${{ deploymentStep }}
                        - ${{ if eq(coalesce(stage.deploymentSteps, false), false) }}:
                          - ${{ each deploymentStep in parameters.deploymentSteps }}:
                            - ${{ deploymentStep }}
                      variables:
                        - ${{ if stage.variables }}:
                          - ${{ each var in stage.variables }}:
                            - ${{ var }}
                - ${{ else }}:
                  - template: ../jobs/wrapper_deployment.yml
                    parameters:
                      artifact: ${{ stage.artifact }}
                      container: ${{ stage.container }}
                      environment: ${{ environment.name }}
                      name: ${{ stage.name }} ${{ environment.name }}
                      steps:
                        - ${{ if parameters.downloadArtifact }}:
                          - task: DownloadPipelineArtifact@2
                            displayName: Download ${{ parameters.artifact }}
                            inputs:
                              allowPartiallySucceededBuilds: true
                              artifact: ${{ parameters.artifact }}
                              pipeline: ${{ parameters.sourcePipeline }}
                              project: $(System.TeamProject)
                              source: specific
                              tags: $(Build.SourceBranchName)
                        - ${{ if parameters.azureAuth }}:
                          - template: ../steps/azure_auth.yml
                            parameters:
                              subscriptionId: $(SUBSCRIPTION_ID)
                        - ${{ if stage.deploymentSteps }}:
                          - ${{ each deploymentStep in stage.deploymentSteps }}:
                            - ${{ deploymentStep }}
                      variables:
                        - ${{ if stage.variables }}:
                          - ${{ each var in stage.variables }}:
                            - ${{ var }}
              pool: ${{ parameters.pool }}
              name: ${{ stage.name }} ${{ environment.name }}
              variables:
                - template: ../variables/environments/${{ lower(environment.name) }}.yml
                - template: ../variables/regions/${{ lower(replace(parameters.region, ' ', '-')) }}.yml
              workingDirectory: ${{ parameters.workingDirectory }}
  - ${{ else }}:
    - ${{ each environment in parameters.environments }}:
      - ${{ each stage in parameters.deploymentStages }}:
        - template: ./wrapper_stage.yml
          parameters:
            condition: ${{ stage.condition }}
            dependsOn:
              - ${{ each dependsOn in environment.dependsOn }}:
                - ${{ replace(replace(stage.name, '-', '_'), ' ', '_') }}_${{ dependsOn }}
              - ${{ if stage.dependsOn }}:
                - ${{ each dependsOnStage in stage.dependsOn }}:
                  - ${{ replace(replace(dependsOnStage, '-', '_'), ' ', '_') }}_${{ environment.name }}
            jobs:
              - ${{ if eq(stage.isDeployment, 'false') }}:
                - template: ../jobs/wrapper_job.yml
                  parameters:
                    container: ${{ stage.container }}
                    name: ${{ stage.name }} ${{ environment.name }}
                    steps:
                      - ${{ if parameters.azureAuth }}:
                        - template: ../steps/azure_auth.yml
                          parameters:
                            subscriptionId: $(SUBSCRIPTION_ID)
                      - ${{ if stage.deploymentSteps }}:
                        - ${{ each deploymentStep in stage.deploymentSteps }}:
                          - ${{ deploymentStep }}
                      - ${{ if eq(coalesce(stage.deploymentSteps, false), false) }}:
                        - ${{ each deploymentStep in parameters.deploymentSteps }}:
                          - ${{ deploymentStep }}
                    variables:
                      - ${{ if stage.variables }}:
                        - ${{ each var in stage.variables }}:
                          - ${{ var }}
              - ${{ else }}:
                - template: ../jobs/wrapper_deployment.yml
                  parameters:
                    artifact: ${{ stage.artifact }}
                    container: ${{ stage.container }}
                    environment: ${{ environment.name }}
                    name: ${{ stage.name }} ${{ environment.name }}
                    steps:
                      - ${{ if parameters.downloadArtifact }}:
                        - task: DownloadPipelineArtifact@2
                          displayName: Download ${{ parameters.artifact }}
                          inputs:
                            allowPartiallySucceededBuilds: true
                            artifact: ${{ parameters.artifact }}
                            pipeline: ${{ parameters.sourcePipeline }}
                            project: $(System.TeamProject)
                            source: specific
                            tags: $(Build.SourceBranchName)
                      - ${{ if parameters.azureAuth }}:
                        - template: ../steps/azure_auth.yml
                          parameters:
                            subscriptionId: $(SUBSCRIPTION_ID)
                      - ${{ if stage.deploymentSteps }}:
                        - ${{ each deploymentStep in stage.deploymentSteps }}:
                          - ${{ deploymentStep }}
                    variables:
                      - ${{ if stage.variables }}:
                        - ${{ each var in stage.variables }}:
                          - ${{ var }}
            pool: ${{ parameters.pool }}
            name: ${{ stage.name }} ${{ environment.name }}
            variables:
              - template: ../variables/environments/${{ lower(environment.name) }}.yml
              - template: ../variables/regions/${{ lower(replace(parameters.region, ' ', '-')) }}.yml
            workingDirectory: ${{ parameters.workingDirectory }}
