parameters:
  - name: azurecrName
    type: string
    default: ''
  - name: authType
    type: string
    default: none
  - name: container
    type: string
    default: ''
  - name: environment
    type: string
    default: dev
  - name: globalVariables
    type: object
    default: []
  - name: pool
    type: object
    default:
      name: pins-odt-agent-pool
    type: string
    default: pins-odt-agent-pool
  - name: projectName
    type: string
    default: ''
  - name: validateName
    type: string
  - name: validationSteps
    type: stepList
    default: []
  - name: variables
    type: object
    default: []
  - name: workingDirectory
    type: string
    default: $(System.DefaultWorkingDirectory)

variables:
  - ${{ each var in parameters.globalVariables }}:
    - ${{ var }}

stages:
- template: ./wrapper_stage.yml
  parameters:
    jobs:
      - template: ../jobs/wrapper_job.yml
        parameters:
          container: ${{ parameters.container }}
          name: ${{ parameters.validateName }}
          steps:
            - checkout: self
              clean: true
              persistCredentials: true
            - ${{ if eq(parameters.authType, 'terraform') }}:
              - template: ../steps/terraform_azure_cli_auth.yml
                parameters:
                  azureServiceConnection: ${{ parameters.projectName }}-${{ parameters.environment }}
            - ${{ if eq(parameters.authType, 'acr') }}:
              - template: ../steps/acr_auth.yml
                parameters:
                  azurecrName: ${{ parameters.azurecrName }}
                  azurecrServiceConnection: ${{ parameters.projectName }}-tooling
            - ${{ each validationStep in parameters.validationSteps }}:
              - ${{ validationStep }}
            - template: ../steps/git_tagging.yml
              parameters:
                tagPrefix: $(Build.Repository.Name)
    pool: ${{ parameters.pool }}
    name: ${{ parameters.validateName }}
    variables:
      - ${{ each var in parameters.variables }}:
        - ${{ var }}
