parameters:
  - name: condition
    type: string
    default: succeeded()
  - name: dependsOn
    type: object
    default: []
  - name: name
    type: string
  - name: jobs
    type: jobList
  - name: poolName
    type: string
    default: pins-odt-agent-pool
  - name: variables
    type: object
    default: []
  - name: workingDirectory
    type: string
    default: $(System.DefaultWorkingDirectory)
  
stages:
  - stage: ${{ replace(replace(parameters.name, '-', '_'), ' ', '_') }}
    variables:
      - ${{ each var in parameters.variables }}:
        - ${{ var }}
    condition: ${{ parameters.condition }}
    dependsOn:
      - ${{ each dependsOn in parameters.dependsOn }}:
        - ${{ dependsOn }}
    displayName: ${{ parameters.name }}
    jobs: 
      - ${{ each job in parameters.jobs }}:
        - ${{ job }}
    pool:
      name: ${{ parameters.poolName }}
