parameters:
  - name: container
    type: string
    default: ''
  - name: environment
    type: string
    default: Dev
  - name: globalVariables
    type: object
    default: []
  - name: project
    type: string
    default: ''
  - name: validateName
    type: string
  - name: validationSteps
    type: stepList
    default: []
  - name: variables
    type: object
    default: []
  - name: workingDirectory
    type: string
    default: $(System.DefaultWorkingDirectory)

variables:
  ${{ each var in parameters.globalVariables }}:
    ${{ var.key }}: ${{ var.value }}

stages:
- template: ./wrapper_stage.yml
  parameters:
    jobs:
      - template: ../jobs/wrapper_job.yml
        parameters:
          container: ${{ parameters.container }}
          environment: ${{ parameters.environment }}
          name: ${{ parameters.validateName }}
          steps:
            - checkout: self
              clean: true
              persistCredentials: true
            - ${{ each validationStep in parameters.validationSteps }}:
              - ${{ validationStep }}
            - template: ../steps/git_tagging.yml
              parameters:
                tagPrefix: $(Build.Repository.Name)
    name: ${{ parameters.validateName }}
    variables:
      - ${{ each variable in parameters.variables }}:
        - ${{ variable }}
