parameters:
  - name: azureAuth
    type: boolean
    default: true
  - name: container
    type: string
    default: ''
  - name: environment
    type: string
    default: dev
  - name: globalVariables
    type: object
    default: []
  - name: pool
    type: object
    default:
      name: pins-odt-agent-pool
  - name: validateName
    type: string
  - name: validationSteps
    type: stepList
    default: []
  - name: workingDirectory
    type: string
    default: $(System.DefaultWorkingDirectory)

variables:
  - ${{ each var in parameters.globalVariables }}:
    - ${{ var }}
  - group: pipeline_secrets

stages:
  - template: ./wrapper_stage.yml
    parameters:
      jobs:
        - template: ../jobs/wrapper_job.yml
          parameters:
            container: ${{ parameters.container }}
            name: ${{ parameters.validateName }}
            steps:
              - checkout: self
                clean: true
                persistCredentials: true
              - template: ../steps/check_branch_name.yml
              - ${{ if parameters.azureAuth }}:
                - template: ../steps/azure_auth.yml
                  parameters:
                    subscriptionId: $(SUBSCRIPTION_ID)
              - ${{ each validationStep in parameters.validationSteps }}:
                - ${{ validationStep }}
              - template: ../steps/git_tagging.yml
                parameters:
                  tagPrefix: $(Build.Repository.Name)
      pool: ${{ parameters.pool }}
      name: ${{ parameters.validateName }}
      variables:
        - template: ../variables/environments/${{ lower(parameters.environment) }}.yml
