parameters:
  - name: appName
    type: string
  - name: artifactName
    type: string
    default: azure-functions
  - name: artifactSourcePipeline
    type: string
  - name: environments
    type: object
    default:
      - name: Dev
      - name: Test
        dependsOn:
          - Dev
      - name: Prod
        dependsOn:
          - Test
  - name: globalVariables
    type: object
    default: []
  - name: project
    type: string
  - name: resourceGroup
    type: string
  - name: variables
    type: object
    default: []
  - name: workingDirectory
    type: string
    default: $(System.DefaultWorkingDirectory)

variables:
  - ${{ each var in parameters.globalVariables }}:
    - ${{ var }}

stages:
  - ${{ each environment in parameters.environments }}:
    - template: ./wrapper_stage.yml
      parameters:
        dependsOn:
          - ${{ each dependsOn in environment.dependsOn }}:
            - Deploy_${{ dependsOn }}
        jobs:
          - template: ../jobs/wrapper_deployment.yml
            parameters:
              environment: ${{ environment.name }}
              name: Deploy ${{ environment.name }}
              steps:
                - template: ../steps/function_app_deploy.yml
                  parameters:
                    appName: ${{ parameters.appName }}
                    artifactName: ${{ parameters.artifactName }}
                    artifactSourcePipeline: ${{ parameters.artifactSourcePipeline }}
                    azureServiceConnection: ${{ parameters.project }}-${{ environment.name }}
                    resourceGroup: ${{ parameters.resourceGroup }}
        name: Deploy ${{ environment.name }}
        variables:
          - template: ../variables/environments/${{ lower(environment.name) }}.yml
          - ${{ each var in parameters.variables }}:
            - ${{ var }}
        workingDirectory: ${{ parameters.workingDirectory }}
